// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: `mysql://${env('MYSQL_USER')}:${env('MYSQL_PASSWORD')}@localhost:3306/${env('MYSQL_DATABASE')}`,
  },
});
